In [42]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [43]:
f = torch.tensor([1, 2, 3], dtype=torch.int64)

In [44]:
print(f)

tensor([1, 2, 3])


In [45]:
choices = nn.ModuleDict({
            'conv': nn.Conv2d(10, 10, 3),
            'pool': nn.MaxPool2d(3)
    })

In [48]:
inputs = torch.randn(2, 2, 2)
filters = torch.randn(2, 2, 2)
F.conv1d(inputs, filters)

tensor([[[1.5829],
         [0.7768]],

        [[0.6515],
         [4.0151]]])

In [57]:
l = torch.tensor([])

In [58]:
print(l)

tensor([])


In [76]:
a = torch.tensor([[1, 1], [1, 1], [1, 1]])
b = torch.tensor([1, 1, 1])
b.matmul(a)

tensor([3, 3])